PathNatureEcommerceCapstone/Controllers/Admin/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PathNatureEcommerceCapstone.Models.DatabaseCapstone;

namespace PathNatureEcommerceCapstone.Controllers.Admin
{
    public class MembersController : Controller
    {
        private PathNatureDbEcommerce db = new PathNatureDbEcommerce();

        // GET: Members
        public ActionResult Index()
        {
            var members = db.Members.Include(m => m.Roles);
            return View(members.ToList());
        }

        // GET: Members/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            return View(members);
        }

        // GET: Members/Create
        public ActionResult Create()
        {
            ViewBag.FK_Member_RoleID = new SelectList(db.Roles, "RoleID", "RoleName");
            return View();
        }

        // POST: Members/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MemberID,FK_Member_RoleID,FirstName,LastName,Username,Email,Password,IsActive,IsDeleted,CreatedAt,LastLogin")] Members members)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(members);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.FK_Member_RoleID = new SelectList(db.Roles, "RoleID", "RoleName", members.FK_Member_RoleID);
            return View(members);
        }

        // GET: Members/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Member_RoleID = new SelectList(db.Roles, "RoleID", "RoleName", members.FK_Member_RoleID);
            return View(members);
        }

        // POST: Members/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MemberID,FK_Member_RoleID,FirstName,LastName,Username,Email,Password,IsActive,IsDeleted,CreatedAt,LastLogin")] Members members)
        {
            if (ModelState.IsValid)
            {
                db.Entry(members).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.FK_Member_RoleID = new SelectList(db.Roles, "RoleID", "RoleName", members.FK_Member_RoleID);
            return View(members);
        }

        // GET: Members/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Members members = db.Members.Find(id);
            if (members == null)
            {
                return HttpNotFound();
            }
            return View(members);
        }

        // POST: Members/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Members members = db.Members.Find(id);
            db.Members.Remove(members);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PathNatureEcommerceCapstone/Controllers/Admin/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PathNatureEcommerceCapstone.Models.DatabaseCapstone;
using PathNatureEcommerceCapstone.Models.Filtri;

namespace PathNatureEcommerceCapstone.Controllers.Admin
{
    public class ProductsController : Controller
    {
        private PathNatureDbEcommerce db = new PathNatureDbEcommerce();

        // GET: Products
        public ActionResult Index()
        {
            var products = db.Products.Include(p => p.Categories);
            return View(products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.FK_Products_CategoriesID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        [HttpPost]
        [SetDateFilterAttribute]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductID,FK_Products_CategoriesID,ProductName,IsActive,IsDeleted,CreatedDate,ModifiedDate,Description,ProductImage,Altdescription,IsFeatured,Quantity,Price")] Products products, HttpPostedFileBase ProductImageFile)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (ProductImageFile != null && ProductImageFile.ContentLength > 0)
                    {
                        // Ottieni il nome del file
                        var fileName = Path.GetFileName(ProductImageFile.FileName);
                        // Salva il file nel percorso desiderato
                        var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                        ProductImageFile.SaveAs(path);
                        // Aggiorna il modello con il percorso dell'immagine salvata
                        products.ProductImage = fileName; // Memorizza solo il nome del file

                    }
                    else
                    {
                        // Se non è stata fornita una nuova immagine, mantieni l'immagine esistente nel database
                        products.ProductImage = "~/Uploads/default.jpg";
                    }

                    // Manipolazione manuale della data prima dell'inserimento nel database
                    products.CreatedDate = DateTime.Now; // Imposta la data di creazione sulla data e ora correnti
                    products.ModifiedDate = DateTime.Now; // Imposta la data di modifica sulla data e ora correnti

                    db.Products.Add(products);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (SqlException ex)
                {
                    // Gestione dell'eccezione per la violazione del vincolo UNIQUE KEY
                    if (ex.Number == 2601 || ex.Number == 2627) // Codici di errore per la violazione del vincolo di chiave unica
                    {
                        ModelState.AddModelError(string.Empty, "Il nome del prodotto è già presente nel database. Inserisci un nome unico.");
                        ViewBag.FK_Products_CategoriesID = new SelectList(db.Categories, "CategoryID", "CategoryName", products.FK_Products_CategoriesID);
                        return View(products);
                    }
                    else
                    {
                        throw; // Se l'eccezione non è relativa alla violazione del vincolo UNIQUE KEY, rilancia l'eccezione
                    }
                }
            }

            // Se si è verificato un errore durante la validazione del modello o il caricamento del file, impostiamo una ViewBag
            ViewBag.ErrorMessage = "Si è verificato un errore durante la creazione del prodotto. Assicurati di compilare tutti i campi obbligatori e di selezionare un file per l'immagine.";

            ViewBag.FK_Products_CategoriesID = new SelectList(db.Categories, "CategoryID", "CategoryName", products.FK_Products_CategoriesID);
            return View(products);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            ViewBag.FK_Products_CategoriesID = new SelectList(db.Categories, "CategoryID", "CategoryName", products.FK_Products_CategoriesID);
            return View(products);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductID,FK_Products_CategoriesID,ProductName,IsActive,IsDeleted,CreatedDate,ModifiedDate,Description,ProductImage,Altdescription,IsFeatured,Quantity,Price")] Products products, HttpPostedFileBase ProductImageFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Se è stata fornita una nuova immagine, caricala e aggiorna il percorso dell'immagine nel modello
                    if (ProductImageFile != null && ProductImageFile.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(ProductImageFile.FileName);
                        var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                        ProductImageFile.SaveAs(path);
                        products.ProductImage = fileName; // Aggiorna il percorso dell'immagine nel modello
                    }

                    // Recupera il prodotto esistente dal database utilizzando l'ID
                    var existingProduct = db.Products.Find(products.ProductID);

                    if (existingProduct != null)
                    {
                        // Sovrascrivi solo le proprietà necessarie
                        existingProduct.FK_Products_CategoriesID = products.FK_Products_CategoriesID;
                        existingProduct.ProductName = products.ProductName;
                        existingProduct.IsActive = products.IsActive;
                        existingProduct.IsDeleted = products.IsDeleted;
                        existingProduct.Description = products.Description;
                        existingProduct.Altdescription = products.Altdescription;
                        existingProduct.IsFeatured = products.IsFeatured;
                        existingProduct.Quantity = products.Quantity;
                        existingProduct.Price = products.Price;

                        // Se è stata fornita una nuova immagine, aggiorna anche il percorso dell'immagine
                        if (ProductImageFile != null && ProductImageFile.ContentLength > 0)
                        {
                            existingProduct.ProductImage = products.ProductImage; // Aggiorna il percorso dell'immagine nel prodotto esistente
                        }

                        // Imposta la data di modifica
                        existingProduct.ModifiedDate = DateTime.Now;

                        // Salva le modifiche nel database
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Prodotto non trovato.");
                    }
                }
            }
            catch (Exception ex)
            {
                // Gestione dell'eccezione
                ModelState.AddModelError(string.Empty, "Si è verificato un errore durante il salvataggio delle modifiche. Riprova più tardi.");
                // Log dell'eccezione per il debug
                // Logger.LogException(ex);
            }

            // Aggiungi il SelectList per le categorie
            ViewBag.FK_Products_CategoriesID = new SelectList(db.Categories, "CategoryID", "CategoryName", products.FK_Products_CategoriesID);

            // Se si verificano errori, torna alla vista con il modello e gli errori di convalida
            return View(products);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Products products = db.Products.Find(id);
            if (products == null)
            {
                return HttpNotFound();
            }
            return View(products);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Products products = db.Products.Find(id);
            db.Products.Remove(products);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PathNatureEcommerceCapstone/Controllers/Admin/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PathNatureEcommerceCapstone.Models.DatabaseCapstone;

namespace PathNatureEcommerceCapstone.Controllers.Admin
{
    public class RolesController : Controller
    {
        private PathNatureDbEcommerce db = new PathNatureDbEcommerce();

        // GET: Roles
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roles roles = db.Roles.Find(id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleID,RoleName")] Roles roles)
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(roles);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(roles);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roles roles = db.Roles.Find(id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        // POST: Roles/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleID,RoleName")] Roles roles)
        {
            if (ModelState.IsValid)
            {
                db.Entry(roles).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(roles);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Roles roles = db.Roles.Find(id);
            if (roles == null)
            {
                return HttpNotFound();
            }
            return View(roles);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Roles roles = db.Roles.Find(id);
            db.Roles.Remove(roles);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PathNatureEcommerceCapstone/Views/Shared/_LayoutPageAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/Content/Assets/Shared/Layout/StyleSheetDashboard.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>


</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index", "Admin")">Start Bootstrap</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li>
                        @*@Html.ActionLink("SignOut", "SignOut", "SignOut", new { area = "" }, new { @class = "dropdown-item" })*@
                    </li>
                </ul>
            </li>
        </ul>
    </nav>

    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>

                        <!-- DASHBOARD -->
                        <a class="nav-link" href="index.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>

                        <!--INTERFACE-->
                        <!--LAYOUT-->
                        <div class="sb-sidenav-menu-heading">Interface</div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Layouts
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>

                        <!--MEMBER-->
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Account and Roles
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>

                        <!--LOG-->
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Members
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="@Url.Action("Index", "Members")">Members Site</a>
                                        <a class="nav-link" href="@Url.Action("Create", "Members")">Register</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>
                        <!--ROLES-->
                        <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Role site
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="@Url.Action("Index", "Roles")">Roles Members</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>


                        <!-- SHOP -->
                        <div class="sb-sidenav-menu-heading">Shop</div>

                        <a class="nav-link" href="@Url.Action("Index", "Products")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Prodotti
                        </a>
                        <a class="nav-link" href="@Url.Action("Index", "Categories")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Categorie
                        </a>
                        <a class="nav-link" href="@Url.Action("Carrello", "#")">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Carrello
                        </a>



                    </div>
                </div>

                <!--SIDEBAR FOOTER-->
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
           
            
            </nav>
        </div>

        <!-- SEZIONE CENTRALE-->
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <div>

                        <div class="col">
                            @RenderBody()
                        </div>.

                        <footer class="py-4 bg-light mt-auto">
                            <div class="container-fluid px-4">
                                <div class="d-flex align-items-center justify-content-between small">
                                    <div class="text-muted">Copyright &copy; Your Website 2023</div>
                                    <div>
                                        <a href="#">Privacy Policy</a>
                                        &middot;
                                        <a href="#">Terms &amp; Conditions</a>
                                    </div>
                                </div>
                            </div>
                        </footer>
                    </div>
                </div>
            </main>

        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>

    <!-- SCRIPT-->
    <script src="~/Scripts/Shared/LayoutAdmin/Script.js"></script>
    <script src="~/Scripts/Shared/LayoutAdmin/database-simple-demo.js"></script>

</body>
</html>